import { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, Sparkles, X, ArrowRight, LoaderCircle } from 'lucide-react'
import type { MediaItem } from '../types/media'
import { Poster } from './MediaCard'

export default function AIPanel({items,onClose,onSelect}:{items:MediaItem[];onClose:()=>void;onSelect:(item:MediaItem)=>void}){const [prompt,setPrompt]=useState('');const [loading,setLoading]=useState(false);const [results,setResults]=useState<MediaItem[]>([]);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>()=>clearTimeout(timer.current),[])
 function generate(){setLoading(true);setResults([]);timer.current=setTimeout(()=>{const q=prompt.toLowerCase();const genres=/fun|laugh|light|comedy/.test(q)?['Comedy']:/tense|crime|thrill|mystery/.test(q)?['Thriller','Crime']:/space|intelligent|sci|mind/.test(q)?['Sci-Fi']:['Drama','Sci-Fi'];const scored=items.filter(i=>i.type==='movie').map(item=>({item,score:item.genres.filter(g=>genres.includes(g)).length*4+(/short|not too long/.test(q)&&item.runtime!<120?6:0)+(item.status==='queued'?1:0)})).sort((a,b)=>b.score-a.score);setResults(scored.slice(0,3).map(s=>s.item));setLoading(false)},800)}
 return <section aria-label="Purate recommendations" className="ai-panel"><div className="ai-header"><div className="ai-brand"><Sparkles size={22}/>Purate<span>FOR YOU</span></div><button className="icon-button" aria-label="Close Purate" onClick={onClose}><X/></button></div><div className="ai-body"><div className="ai-emblem"><Sparkles size={30}/></div><h1>Your next favourite<br/>starts with a feeling.</h1><p>What should I watch next? Tell me your mood.<br/>Let’s find something that stays with you.</p><form onSubmit={e=>{e.preventDefault();generate()}}><label className="field-label" htmlFor="mood">What are you in the mood for?</label><textarea id="mood" placeholder="Something intelligent, tense and not too long" value={prompt} onChange={e=>setPrompt(e.target.value)}/><div className="mood-chips">{['A little escapism','Smart & tense','Make me laugh'].map(mood=><button key={mood} type="button" onClick={()=>setPrompt(mood)}>{mood}</button>)}</div><button className="primary-button generate" disabled={loading}>{loading?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {loading?'Finding your next favourite…':'Generate recommendations'}{!loading&&<ArrowRight size={18}/>}</button></form>{results.length>0&&<div className="recommendations"><div className="recommendations-label"><span>MADE FOR YOUR MOOD</span><span>3 picks</span></div>{results.map((item,i)=><button className="recommendation" key={item.id} onClick={()=>onSelect(item)}><Poster item={item}/><div><small><Sparkles size={11}/> AI recommendation</small><h3>{item.title}</h3><span className="recommendation-meta">{item.year} · {item.runtime} min</span><p>{i===0?`A ${item.genres[0].toLowerCase()} pick with an absorbing story, made for the mood you described.`:i===1?'For when you want rich characters and a story that keeps you thinking long after the credits.':'A change of pace with a distinctive point of view. Your next unexpected favourite.'}</p></div><ArrowUpRight size={17}/></button>)}</div>}<div className="ai-footer">A little less scrolling. A little more discovery.</div></div></section>
}


