import { useEffect, useState } from 'react'
import { Sparkles, SearchX, X, Check } from 'lucide-react'
import Sidebar from './components/Sidebar'
import Toolbar from './components/Toolbar'
import MediaGrid from './components/MediaGrid'
import MediaList from './components/MediaList'
import MediaModal from './components/MediaModal'
import AIPanel from './components/AIPanel'
import Dialog from './components/Dialog'
import { useMediaLibrary } from './hooks/useMediaLibrary'
import { statuses, type MediaItem, type MediaStatus, type MediaType, type Sort } from './types/media'
const infoText:Record<string,string>={"What's New":'Meet TasteAI. Your movies, shows, and books now share one home. Keep notes, rate your favourites, and find your next great watch with mood-based recommendations.','Help & Tips':'Choose a media type and status to browse your library. Click any cover to change its status, add a star rating, or write a note. Use Filter and Search together to narrow things down. Your changes are saved in this browser.','Feedback & Support':'TasteAI is a standalone demo. If something looks wrong, try clearing your filters or reloading the page. Your saved library stays in this browser.','Settings':'Your library is stored locally on this device. No account is needed. This edition uses the Forest dark theme.','Install mobile app':'Open TasteAI in your phone’s browser, then use the browser menu and choose “Add to Home Screen” to keep a shortcut close by.','Import existing library':'This demo includes a starter library of 32 movies, TV shows, and books. You can make it yours by opening a title and updating its status, rating, and notes. External library imports are not available in this edition.'}
function initialRoute(){const parts=window.location.pathname.split('/');return {type:({movies:'movie',tv:'tv',books:'book'} as Record<string,MediaType>)[parts[4]]||'movie',status:statuses.includes(parts[5] as MediaStatus)?parts[5] as MediaStatus:'queued' as MediaStatus}}
export default function App(){const {items,update,filter,error}=useMediaLibrary();const [type,setType]=useState<MediaType>(initialRoute().type);const [status,setStatus]=useState<MediaStatus>(initialRoute().status);const [genre,setGenre]=useState('All genres');const [sort,setSort]=useState<Sort>('Log date');const [query,setQuery]=useState('');const [view,setView]=useState<'grid'|'list'>('grid');const [selected,setSelected]=useState<MediaItem|null>(null);const [ai,setAI]=useState(false);const [section,setSection]=useState('Track');const [info,setInfo]=useState('');const [toast,setToast]=useState('');
 useEffect(()=>{window.history.replaceState({},'',`/track/u/orion/${{movie:'movies',tv:'tv',book:'books'}[type]}/${status}`)},[type,status]);useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(timer)}},[toast])
 const visible=section==='Track'?filter(type,status,genre,query,sort):items.filter(i=>i.type===type&&(section==='Explore'||(i.rating||0)>=4)&&(genre==='All genres'||i.genres.includes(genre))&&i.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Title'?a.title.localeCompare(b.title):sort==='Year'?b.year-a.year:sort==='Rating'?(b.rating||0)-(a.rating||0):b.addedAt.localeCompare(a.addedAt))
 return <div className="app"><Sidebar section={section} onSection={setSection} onInfo={setInfo}/><main><Toolbar type={type} status={status} genre={genre} sort={sort} query={query} view={view} setType={v=>{setType(v);setGenre('All genres')}} setStatus={v=>{setStatus(v);setSection('Track')}} setGenre={setGenre} setSort={setSort} setQuery={setQuery} setView={setView}/>{section!=='Track'&&<div className="section-heading"><span className="eyebrow">{section==='Curate'?'THE GOOD STUFF':'FOLLOW YOUR CURIOSITY'}</span><h1>{section==='Curate'?'Your favourites, together.':'A world of great stories.'}</h1><p>{section==='Curate'?'A collection of everything you’ve rated four stars or more.':'Discover something new from the TasteAI collection.'}</p></div>}{visible.length?(view==='grid'?<MediaGrid items={visible} onSelect={setSelected}/>:<MediaList items={visible} onSelect={setSelected}/>):<div className="empty-state"><SearchX size={38}/><h2>Nothing here yet.</h2><p>Try changing your filters.</p><button className="secondary-button" onClick={()=>{setGenre('All genres');setQuery('');setStatus('queued');setSection('Track')}}>Reset filters</button></div>}</main><button className="ai-fab" title="Ask TasteAI" aria-label="Ask TasteAI" onClick={()=>setAI(true)}><Sparkles size={28}/><span>Ask TasteAI</span></button>{selected&&<MediaModal key={selected.id} item={selected} onClose={()=>setSelected(null)} onSave={item=>{update(item);setSelected(null);setToast('Changes saved to your library')}}/>}{ai&&<AIPanel items={items} onClose={()=>setAI(false)} onSelect={item=>{setAI(false);setSelected(item)}}/>}{info&&<Dialog label={info} onClose={()=>setInfo('')} className="info-modal"><button className="close-button" aria-label="Close" onClick={()=>setInfo('')}><X/></button><span className="eyebrow">TASTEAI</span><h1>{info}</h1><p>{infoText[info]}</p><button className="primary-button" onClick={()=>setInfo('')}>Got it</button></Dialog>}{(toast||error)&&<div className="toast" role="status"><Check size={17}/>{error||toast}</div>}</div>
}
